# _config.yml — GovernAI.pro
title: GovernAI.pro
email: contact@governai.pro
description: >- 
  Data & AI Governance for Strategy Leaders. 
  Curated insights, tools, and implementation guides for public sector transformation.

baseurl: "" # Leave empty unless you're using a project page (e.g., /repo-name/)
url: "https://egilui.github.io" # Change to your GitHub Pages user/org domain if needed
# url: "https://governai.pro" # Uncomment when ready for custom domain

theme: # Leave blank — using Norlin locally via layouts/includes

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Optional: Social Media + SEO (customise later)
author:
  name: Egidijus Luinevicius
  email: contact@governai.pro
