# Site Metadata
name: 'GovernAI.pro'
description: 'Data & AI Governance for Strategy Leaders. Curated insights, tools, and implementation guides for public sector transformation.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
email: 'governaipro@gmail.com'
url: 'https://governai.pro'
baseurl: ''  # Keep empty for custom domains like https://governai.pro

# Discussion / Subscriptions (optional)
disqus: ''            # Add your Disqus shortname here if enabled
mailchimp-list: ''    # Add your Mailchimp form action URL if integrating

# Navigation & Routing
include: ["_pages"]   # Allow standalone pages
permalink: /:title/   # Clean URLs like /step-1-data-leadership/

# Plugins
plugins: 
  - jekyll-feed       # RSS feed
  - jekyll-sitemap    # sitemap.xml
  - jekyll-paginate   # pagination
  - jekyll-seo-tag    # Open Graph + SEO meta

# Author Profile
authors:
  egidijus:
    name: Egidijus Luinevicius
    site: https://governai.pro
    avatar: /assets/images/avatar1.jpg
    bio: "Founder of GovernAI.pro — exploring open data, AI strategy, and digital innovation for the public sector."
    email: governaipro@gmail.com
    linkedin: https://www.linkedin.com/in/egidijuslu/

# Global Default Values
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: egidijus
      avatar: /assets/images/avatar1.jpg
      
  - scope:
      path: "_pages"
    values:
      layout: page

# Markdown Rendering
markdown: kramdown
highlighter: rouge

# Pagination (10 posts per page)
paginate: 10


# Exclude unnecessary dev files
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules

