# Site
name: 'GovernAI.pro'
description: 'Data & AI Governance for Strategy Leaders. Curated insights, tools, and implementation guides for public sector transformation.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''  # Leave empty for user/organization site or when using a custom domain
url: 'https://egilui.github.io'  # Change to custom domain (https://governai.pro) when ready
email: 'contact@governai.pro'
disqus: ''  # Leave empty or update if you set up Disqus
mailchimp-list: ''  # Leave empty unless integrating newsletter

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    egidijus:
      name:           Egidijus Luinevicius
      site:           https://governai.pro
      avatar:         /assets/images/avatar1.jpg  # Replace with your own photo if desired
      bio:            "Founder of GovernAI.pro — exploring open data, AI strategy, and digital innovation for the public sector."
      email:          contact@governai.pro
      twitter:        https://twitter.com/egidijuslu  # Optional: update with your actual Twitter handle

# Defaults
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: egidijus
      avatar: /assets/images/avatar1.jpg
      
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10

# Exclude metadata and dev dependencies
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
