title: GovernAI.pro
email: your@email.com
description: >- # this means to ignore newlines until next key
  AI & Data Strategy for Leaders

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://egilui.github.io" # or your custom domain

# disable default theme
theme: null

# directories
source: .
destination: ./_site
markdown: kramdown
highlighter: rouge

# Jekyll options
future: true
lsi: false
incremental: false

permalink: pretty

collections:
  posts:
    output: true

# exclude folders from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# optional plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
