# _config.yml — GovernAI.pro

title: GovernAI.pro
email: contact@governai.pro
description: >-
  Data & AI Governance for Strategy Leaders.
  Curated insights, tools, and implementation guides for public sector transformation.

baseurl: "" # Leave empty unless you're using a project page (e.g., /repo-name/)
url: "https://egilui.github.io" # Use your GitHub Pages domain (change to custom later)
# url: "https://governai.pro" # Uncomment when DNS is configured for custom domain

# theme: norlin # Not required — using Norlin locally via _layouts/ and _includes

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Optional: Author & SEO metadata
author:
  name: Egidijus Luinevicius
  email: egidijus.lu@icloud.com
