title: GovernAI.pro
email: your.email@example.com
description: >-
  Articles and strategies on Data & AI Governance for public sector leaders.
baseurl: "" # leave this empty unless you're using a subdirectory
url: "https://governai.pro"

# Author settings
author:
  name: Egidijus Luinevicius
  email: your.email@example.com

# Social settings
twitter_username: egilui
github_username: EgiLui
linkedin_username: egidijus-luinevicius

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
